name: spotless-check
on: [push]
jobs:
  spotless-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: iot-benchmark
      - name: spotless-check
        run: |
          cd ${{ github.workspace }}/iot-benchmark
          mvn spotless:check
